### ISSUE TITLE
ClassVariables cannot be committed as extensions

### ISSUE THREAD

**Issue by guillep** [rajula96reddy/pharo-cli#1]
you can only extend using extension methods. But so far there is no such thing as "extension variables".

Thus, this method does not work when you download it in a fresh image:
```smalltalk
defaultMaximumPathLength
	"This method defines the default maximum path length for the getPwdViaFFi:Size: and getCurrentWorkingDirectory implementation"
	 PathLength := 4096.
	^PathLength 
```

I'd suggest a slighty simpler version?

```smalltalk
defaultMaximumPathLength
	"This method defines the default maximum path length for the getPwdViaFFi:Size: and getCurrentWorkingDirectory implementation"
	 ^ 4096
```

What do you think?

**Comment by guillep** [comment]
And of course, methods using the default path should always call the method, not use the variable (that may be not initialized if you never ask for the default path length:

```smalltalk
getCurrentWorkingDirectory
	"This method calls the method getPwdViaFFI with arugement of a buffer size."
	|buffer |
	buffer := String new: self defaultMaximumPathLength.
	^self getPwdViaFFI: buffer size: self defaultMaximumPathLength. 
```

**Comment by rajula96reddy** [comment]
Yeah, even I had the doubt whether to have the pathlength as a class variable or not. Like you said, it is good to just return the length. And yeah, I should call the method not the variable if I am using one. I will make the changes.

**Comment by guillep** [comment]
Also the problem with the variable is that you need to initialize it somewhere, and as you did, the initialization code is not called automatically. Just be careful with that kind of things. If you don't know how to do some of these things (e.g., how to initialize class variables) you can ask in the mailing list :)

**Comment by guillep** [comment]
Cool, can we close this issue then?

**Comment by rajula96reddy** [comment]
Yup. The issue is solved.
