### ISSUE TITLE
Factor out the repeated code

### ISSUE THREAD

**Issue by guillep** [rajula96reddy/pharo-cli#3]
You can move the common code:
- `getCurrentWorkingDirectory`
- `getCurrentWorkingDirectoryWithSize:`
to the common `OSPlatform` superclass.

Also, you can define in the superclass some abstract methods for:

- `defaultMaximumPathLength`
- `getPwdViaFFI: arg1 size: arg2`

You can define abstract methods as follows:

```smalltalk
getPwdViaFFI: arg1 size: arg2
  self subclassResponsibility
```

**Comment by rajula96reddy** [comment]
Ok. Cool. I will define abstract methods.

**Comment by guillep** [comment]
Nice, to close this one, there is still one little step:

```smalltalk
getCurrentWorkingDirectory
	"This method calls the method getPwdViaFFI with argument of a buffer size."
	|buffer |
	buffer := String new: self defaultMaximumPathLength  .
	^self getPwdViaFFI: buffer size:self defaultMaximumPathLength . 
```

is really similar to `getCurrentWorkingDirectoryWithSize:`

Cannot `getCurrentWorkingDirectory` be defined in terms of `getCurrentWorkingDirectoryWithSize:` ? 

```smalltalk
getCurrentWorkingDirectory
    ^ self getCurrentWorkingDirectoryWithSize: self defaultMaximumPathLength .
```

**Comment by rajula96reddy** [comment]
Oh! Yeah. Reusing the existing code. Cool. Will change it.
